# Приветствую! Это конфиг с настройками AuthTG
# Hi! This is a config with AuthTG settings
bot: # Настройки бота EN: Settings of bot
  token: "changeme" # Токен бота EN: Bot token
  username: "changeme" # Имя бота EN: Bot username
mysql: # Настройки базы данных EN: Database settings
  use: false # Использовать базу данных EN: Use database
  host: "localhost" # Хост базы данных,УКАЗЫВАЙТЕ ТУТ ЖЕ ПОРТ,ЕСЛИ ИСПОЛЬЗУЕТСЯ EN: Host of database, ENTER HERE PORT IF YOU USE
  db: "AuthTG" # Имя базы данных EN: Database name
  user: "root" # Имя пользователя EN: Username
  pass: "123" # Пароль EN: Password
macro:
  # Example | Пример
  # testcmd: - Команда,которая будет в тг EN: Command that will be in tg
    # mccmd: "whitelist [arg1] [arg2]" - Команда,которая будет вызываться в боте (если есть аргументы к команде,прописывайте их [arg1] и т.д.) EN: Command that will be called in the bot (if there are arguments to the command, write them [arg1] and so on.)
    # nsmsg: "test" - Сообщение,которое будет написано если введена обычная команда без аргументов (В этом сообщении обычно указывается: "Введите аргументы для команды") EN: Message that will be written if the normal command is entered without arguments (In this message it is usually specified: "Enter the arguments for the command")
mutecommands: ["/tell"] # Команды, которые нельзя использовать EN: Commands that cannot be used
commandsPreAuthorization: ["/tell"] # Команды,которые будут доступны перед авторизацией EN: Commands that will be available before
notRegAndLogin: false # Без /register и /login EN: Without /register and /login
authNecessarily: false # Обязательная авторизация EN: Necessary authorization
minLenghtNickname: 3 # Минимальная длина ника EN: Min length nickname
maxLenghtNickname: 15 # Максимальная длина ника EN: Max length nickname
minLenghtPassword: 3 # Минимальная длина пароля EN: Min length password
maxLenghtPassword: 32 # Максимальная длина пароля EN: Max length password
timeoutSession: 60 # Время в минутах,через которое у игрока сбросится сессия EN: Time in minutes after which the player will reset the session
kickTimeout: 30 # Время в секундах, через которое игрок будет кикнут если не авторизовался EN: Time in seconds, after which the player will be kicked if not authorized
activeChatinTG: true # Должен ли работать чат в телеграме EN: Must chat in Telegram
spawn: # Спавн EN: Spawn
  x: 0
  y: 0
  z: 0
  world: "none"